# Dekomposisi LU


In [1]:
import numpy as np

# Fungsi untuk mencetak matriks
def print_matrix(matrix):
    for row in matrix:
        print(row)

# Fungsi dekomposisi LU dengan pivot matriks
def lu_decomposition_pivot(matrix):
    n = len(matrix)
    P = np.identity(n)  # Matriks identitas untuk merekam operasi pivot
    L = np.zeros((n, n))
    U = np.copy(matrix)

    for k in range(n):
        # Pilih pivot (elemen maksimum pada kolom k)
        pivot_row = np.argmax(abs(U[k:, k])) + k

        # Tukar baris dalam matriks U
        U[[k, pivot_row]] = U[[pivot_row, k]]

        # Tukar baris dalam matriks P
        P[[k, pivot_row]] = P[[pivot_row, k]]

        L[k, k] = 1  # Set 1 di diagonal L

        for i in range(k+1, n):
            factor = U[i, k] / U[k, k]
            L[i, k] = factor
            U[i, k:] -= factor * U[k, k:]

    return P, L, U

# Fungsi dekomposisi LU dengan OBE
def lu_decomposition_obe(matrix):
    n = len(matrix)
    L = np.identity(n)
    U = np.copy(matrix)

    for k in range(n):
        for i in range(k+1, n):
            factor = U[i, k] / U[k, k]
            L[i, k] = factor
            U[i, k:] -= factor * U[k, k:]

    return L, U

# Meminta pengguna untuk memasukkan matriks
n = int(input("Masukkan ukuran matriks (n): "))
matrix = []
print("Masukkan elemen-elemen matriks:")
for _ in range(n):
    row = list(map(float, input().split()))
    matrix.append(row)

# Dekomposisi LU dengan pivot matriks
P, L, U = lu_decomposition_pivot(np.array(matrix))
print("\nDekomposisi LU dengan Pivot Matriks:\n")
print("Matriks P:")
print_matrix(P)
print("Matriks L:")
print_matrix(L)
print("Matriks U:")
print_matrix(U)

# Dekomposisi LU dengan OBE
L, U = lu_decomposition_obe(np.array(matrix))
print("\n\nDekomposisi LU dengan OBE:\n")
print("Matriks L:")
print_matrix(L)
print("Matriks U:")
print_matrix(U)

Masukkan ukuran matriks (n): 3
Masukkan elemen-elemen matriks:
1 2 3
5 7 1
4 3 1

Dekomposisi LU dengan Pivot Matriks:

Matriks P:
[0. 1. 0.]
[0. 0. 1.]
[1. 0. 0.]
Matriks L:
[1. 0. 0.]
[0.2 1.  0. ]
[ 0.8        -0.23076923  1.        ]
Matriks U:
[5. 7. 1.]
[ 0.  -2.6  0.2]
[0.         0.         2.84615385]


Dekomposisi LU dengan OBE:

Matriks L:
[1. 0. 0.]
[5. 1. 0.]
[4.         1.66666667 1.        ]
Matriks U:
[1. 2. 3.]
[  0.  -3. -14.]
[ 0.          0.         12.33333333]
